### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Kalimon12** [chvancooten/BugBountyScanner#10]
-severity low,medium,high not work in nuclei

**Comment by chvancooten** [comment]
What version of Nuclei are you running? Could you please paste the error you are getting here?

**Comment by Kalimon12** [comment]
nuclei v2.1

**Comment by chvancooten** [comment]
It should be working in Nuclei v2.1.1 which is installed by the script. Could you please install the latest version of Nuclei and try again? (It's merged [here](https://github.com/projectdiscovery/nuclei/pull/199)).

**Comment by Kalimon12** [comment]
working sorry pro Thank you  
you can add some tools like cookieless hinject

**Comment by chvancooten** [comment]
Glad to hear it :) 
Nuclei should be able to detect host header injection vulnerabilities. I'm not aware of Cookieless, but for XSS I was thinking of implementing Dalfox. Other suggestions are of course very welcome! To be continued!
