### ISSUE TITLE
Aquatone

### ISSUE THREAD

**Issue by anasbousselham** [chvancooten/BugBountyScanner#36]
Hi,
Aquatone is better than webscreenshot!

**Comment by chvancooten** [comment]
Thanks for the suggestion, @anasbousselham! I'll keep this ticket open as an enhancement request for when I find the time to look into it. Do note that I don't have a lot of bandwidth to work on BugBountyScanner at the moment, so pull requests are more than welcome :)

**Comment by Xitro01** [comment]
I'm not very good with pull requests, but it should be as easy as replacing:
`webscreenshot -i "livedomains-$DOMAIN.txt" -o webscreenshot --no-error-file`
With:
`cat livedomains-$DOMAIN.txt | aquatone -ports xlarge`
Then it generates a HTML page with all screenshots.

Then all it needs is some changes in names and replacing commands in install.sh to install aquatone, something like:
`go get -u github.com/michenriksen/aquatone`

**Comment by theinit01** [comment]
@chvancooten, can I work on this please? Assign this to me
