### ISSUE TITLE
Phantomjs is removed from Kali repo

### ISSUE THREAD

**Issue by aancw** [chvancooten/BugBountyScanner#37]
Hi, 

Just want to let you know that phantomjs is removed from Kali repo: pkg.kali.org/pkg/phantomjs

![image](https://user-images.githubusercontent.com/6284204/114499352-1a731b00-9c50-11eb-8540-757508a8e582.png)

**Comment by chvancooten** [comment]
Thanks for the heads-up! This will probably become a breaking change for Kali users running the "manual" `setup.sh` installation fairly soon.

Workaround for now is to use the Docker version (which I would recommend in any case) - but will definitely queue this as a fix for the setup script. Should definitely be possible to automate installation of a stable PhantomJS version from [here](https://phantomjs.org/download.html).
