### ISSUE TITLE
Replace GoBuster with FFUF

### ISSUE THREAD

**Issue by chvancooten** [chvancooten/BugBountyScanner#38]
Based on a request and some discussion on Twitter, this sounds like a better alternative. Need to look into this to determine if that's true, and if so implement it.

**Comment by theinit01** [comment]
@chvancooten, if this is not done yet, Can you please assign this to me?

**Comment by chvancooten** [comment]
Hey @theinit01, sure thing - feel free to work on this! I'm currently abroad and unable to test or review changes but your edits will be most welcome!
