### ISSUE TITLE
not install tools 

### ISSUE THREAD

**Issue by Kalimon12** [chvancooten/BugBountyScanner#9]
how install DEPENDENCIES

**Comment by chvancooten** [comment]
The script installs the dependencies (except `nmap` and `amass` at this point) automatically if it does _not_ find the `subjack` binary installed (very crude check, I know). It should echo that it is installing dependencies on first run.  If you have `subjack` installed but not the other binaries, you can manually run the commands listed in the code. It is still on my list to create a separate and complete installation script (ref. #4 and #3).

If you are encountering any errors upon first run and you have `nmap` and `amass` pre-installed, please paste them here!
